# generated with:
# code --list-extensions | xargs -L 1 echo code --install-extension

code --install-extension abusaidm.html-snippets
code --install-extension amandeepmittal.pug
code --install-extension andrew-codes.cypress-snippets
code --install-extension anseki.vscode-color
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension arthurwhite.white
code --install-extension azemoh.one-monokai
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension cssho.vscode-svgviewer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension everettjf.filter-line
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-close-tag
code --install-extension Gruntfuggly.todo-tree
code --install-extension herrmannplatz.npm-dependency-links
code --install-extension HookyQR.beautify
code --install-extension hwencc.html-tag-wrapper
code --install-extension James-Yu.latex-workshop
code --install-extension jithurjacob.nbpreviewer
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension leizongmin.node-module-intellisense
code --install-extension michelemelluso.code-beautifier
code --install-extension michelemelluso.gitignore
code --install-extension mkaufman.HTMLHint
code --install-extension mkxml.vscode-filesize
code --install-extension mrmlnc.vscode-pugbeautify
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension naumovs.color-highlight
code --install-extension PKief.material-icon-theme
code --install-extension techer.open-in-browser
code --install-extension tht13.html-preview-vscode
code --install-extension vangware.dark-plus-material
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
code --install-extension whizkydee.material-palenight-theme
code --install-extension xabikos.JasmineSnippets
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
code --install-extension ziyasal.vscode-open-in-github